### ISSUE TITLE
Hacer el AST de acuerdo a la Gramatica Definida

### ISSUE THREAD

**Issue by OmarHernandez99** [CSProjectsAvatar/ml#5]
Inside `1st-project/domain/AST/ast_node.py` some AST-node classes are defined. You must complete the definition of all classes shown in `1st-project/grammars/ast-query-cypher.pdf`.

See branch `feat/ast5` and work upon it.

**Comment by MakeMake23** [comment]
a few `Optional` must be deleted. That's mine
